// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXQ4tqNexp_2I63SLxt2vLbMgtdLqCvMQ',
    appId: '1:161181161682:android:d459159de58c2ccdfcb50b',
    messagingSenderId: '161181161682',
    projectId: 'monitoring-air-quality-b0c30',
    databaseURL: 'https://monitoring-air-quality-b0c30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoring-air-quality-b0c30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRi6V5U1r3YQE1BhJP1c3oYZM2VfyGEtU',
    appId: '1:161181161682:ios:6c3c3302addeb4a1fcb50b',
    messagingSenderId: '161181161682',
    projectId: 'monitoring-air-quality-b0c30',
    databaseURL: 'https://monitoring-air-quality-b0c30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoring-air-quality-b0c30.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAirQuality2',
  );
}
